"""empty message

Revision ID: c4064a949daa
Revises: c797785b1e10
Create Date: 2020-01-08 22:12:55.642556

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c4064a949daa'
down_revision = 'c797785b1e10'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('todo_item')
    op.drop_table('todo')
    op.add_column('SurveyInfo', sa.Column('interests', sa.String(length=80), nullable=True))
    op.add_column('SurveyInfo', sa.Column('year', sa.String(length=80), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('SurveyInfo', 'year')
    op.drop_column('SurveyInfo', 'interests')
    op.create_table('todo',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('name', sa.VARCHAR(length=80), nullable=True),
    sa.Column('tag', sa.VARCHAR(length=80), nullable=True),
    sa.Column('pub_date', sa.DATETIME(), nullable=True),
    sa.Column('uid', sa.INTEGER(), nullable=True),
    sa.ForeignKeyConstraint(['uid'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('todo_item',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('task', sa.VARCHAR(length=80), nullable=True),
    sa.Column('pub_date', sa.DATETIME(), nullable=True),
    sa.Column('uid', sa.INTEGER(), nullable=True),
    sa.Column('tid', sa.INTEGER(), nullable=True),
    sa.ForeignKeyConstraint(['tid'], ['todo.id'], ),
    sa.ForeignKeyConstraint(['uid'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###
